# --- Search Results HTML String ---
# This will display the user's query and the result from the Gemini API
SEARCH_RESULTS_HTML = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MindWork: Search Results</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        body { font-family: 'Inter', sans-serif; }
        .primary-blue { color: #1f4e79; }
        .bg-primary-blue { background-color: #1f4e79; }
    </style>
</head>
<body class="bg-gray-100 min-h-screen">
    <header class="bg-white shadow-lg">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
             <a href="/" class="text-2xl font-extrabold primary-blue">MindWork</a>
        </div>
    </header>
    <main class="max-w-4xl mx-auto p-8">
        <h1 class="text-3xl font-extrabold text-gray-900 mb-6">Research Results</h1>
        
        <div class="bg-white p-6 rounded-xl shadow-lg mb-8">
            <h2 class="text-xl font-semibold primary-blue mb-3">Query: "{{ user_query }}"</h2>
            <p class="text-sm text-gray-500">
                Analysis generated by Google Gemini.
            </p>
        </div>

        <div class="bg-white p-8 rounded-xl shadow-2xl">
            <h2 class="text-2xl font-bold primary-blue mb-4 border-b pb-2">Gemini Analysis</h2>
            {% if search_result %}
                <pre class="whitespace-pre-wrap text-gray-700 leading-relaxed">{{ search_result }}</pre>
            {% else %}
                <p class="text-gray-500">No results were returned for your query.</p>
            {% endif %}
        </div>
    </main>
</body>
</html>
"""